org: hobby31
service: report-service

useDotEnv: true

provider:
    name: aws
    runtime: nodejs20.x
    region: sa-east-1
    profile: personal
    memorySize: 128
    environment:
        DYNAMO_LEADS_TABLE: !Ref LeadsTable
        GENERATE_REPORT_QUEUE_URL: !Ref GenerateReportQueue
        REPORTS_BUCKET_NAME: !Ref ReportsBucket
        RESEND_API_KEY: ${env:RESEND_API_KEY}
    iam:
        role:
            statements:
                # Dynamo DB
                - Effect: Allow
                  Resource: !GetAtt LeadsTable.Arn
                  Action:
                      - dynamodb:PutItem
                      - dynamodb:Scan
                # SQS
                - Effect: Allow
                  Resource: !GetAtt GenerateReportQueue.Arn
                  Action:
                      - sqs:SendMessage
                # SE
                - Effect: Allow
                  Action:
                      - s3:PutObject
                      - s3:AbortMultipartUpload
                      - s3:GetObject
                  Resource: !Join ["/", [!GetAtt ReportsBucket.Arn, "*"]]

package:
    individually: true

build:
    esbuild:
        bundle: true
        minify: true
        sourcemap: false
        exclude:
            - "@aws-sdk/*"

functions:
    populateDynamo:
        handler: src/functions/http/populate-dynamo.handler
        timeout: 25
        events:
            - httpApi:
                  path: /populate-dynamo
                  method: POST
    generateReport:
        handler: src/functions/http/generate-report.handler
        events:
            - httpApi:
                  path: /generate-report
                  method: POST
    processReport:
        handler: src/functions/queues/process-report.handler
        timeout: 180
        events:
            - sqs:
                  arn: !GetAtt GenerateReportQueue.Arn
                  batchSize: 1

resources:
    - ${file(./resources/dynamodb/LeadsTable.yml)}
    - ${file(./resources/sqs/GenerateReportQueue.yml)}
    - ${file(./resources/s3/ReportsBucket.yml)}
